### ISSUE TITLE
RecursionError when using small RAM mode

### ISSUE THREAD

**Issue by mareikethies** [RUB-Bioinf/VesselExpress#5]
Hi, 
thanks for sharing this project. I am running your code directly from python by modifying the Snakemake file (the reason is that I am mainly interested in the graph analysis part of your pipeline). My problem occurs in the graph analysis step when turning on the smallRAMmode flag. Without that flag, I am running out of memory during the Euclidean distance transform on a machine with 64GB of RAM on my data. With that flag enabled, I get a python RecursionError caused somewhere inside the dask package. The exact error is `RecursionError: maximum recursion depth exceeded while calling a Python object`.

Parts of the stacktrace are:
```Traceback (most recent call last):
  File ".../VesselExpress/VesselExpress/modules/filament.py", line 124, in dfs_iterative
    self._removeSmallAndSegmentsBelowDiameterLengthRatio(self.cut_neighbor_brpt_segs)
  File ".../VesselExpress/VesselExpress/modules/filament.py", line 420, in _removeSmallAndSegmentsBelowDiameterLengthRatio
    if (self.segmentStats[segKey]['length'] < self.diaScale * self.segmentStats[segKey]['diameter']\
  File ".../site-packages/dask/array/core.py", line 1679, in __bool__
    return bool(self.compute())
  File ".../site-packages/dask/base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File ".../site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File ".../site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File ".../site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File ".../site-packages/dask/local.py", line 315, in reraise
    raise exc
  File ".../site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File ".../site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File ".../site-packages/dask/optimization.py", line 969, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File ".../site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File ".../site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File ".../site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File ".../site-packages/dask/core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]
...

RecursionError: maximum recursion depth exceeded while calling a Python object
```   

I have version 2021.11.0 of dask installed and I am running python 3.9. Do you have any ideas what could cause this error? Interestingly, when I debug the exact same code from within an IDE, the error does not occur and everything runs just fine. Any ideas would be appreciated.

**Comment by mareikethies** [comment]
It seems like I figured it out. Below, see the diff files of the changes that I made to your code to avoid the above issue. Let me know if you want me to explain anything or create a pull request.

Changes to ./VesselExpress/modules/measurements.py
```diff --git a/VesselExpress/modules/measurements.py b/VesselExpress/modules/measurements.py
index 3f2dc12..53a2bc0 100644
--- a/VesselExpress/modules/measurements.py
+++ b/VesselExpress/modules/measurements.py
@@ -30,10 +30,17 @@ def getLength(path, dimensions):
     return length
 
 
-def getRadius(distTrans, segment):
+def getRadius(distTrans, segment, smallRAMmode=0):
     sumRadii = 0
-    for skelPt in segment:
-        sumRadii += distTrans[skelPt]
+    if not smallRAMmode:
+        for skelPt in segment:
+            sumRadii += distTrans[skelPt]
+    else:
+        for i, skelPt in enumerate(segment):
+            sumRadii += distTrans[skelPt]
+            if i % 100 == 99:
+                sumRadii = sumRadii.compute()
+        sumRadii = sumRadii.compute()
     return sumRadii / len(segment)
```

Changes to ./VesselExpress/modules/filament.py
```diff --git a/VesselExpress/modules/filament.py b/VesselExpress/modules/filament.py
index 5723bd7..2cdee4f 100644
--- a/VesselExpress/modules/filament.py
+++ b/VesselExpress/modules/filament.py
@@ -281,7 +281,7 @@ class Filament:
         """
         self.segmentsDict[segment[0], segment[len(segment) - 1]] = segment
         if self.smallRAMmode == 1:
-            radius = ms.getRadius(da.from_zarr('tmp_zarr' + os.sep + self.fileName + '_radiusMatrix.zarr'), segment)
+            radius = ms.getRadius(da.from_zarr('tmp_zarr' + os.sep + self.fileName + '_radiusMatrix.zarr'), segment, 1)
         else:
             radius = ms.getRadius(self.skelRadii, segment)
 
@@ -302,7 +302,7 @@ class Filament:
         if interpolate:
             if self.smallRAMmode == 1:
                 volume = ms.getVolume(da.from_zarr('tmp_zarr' + os.sep + self.fileName + '_radiusMatrix.zarr'),
-                                      coords, self.pixelDims)
+                                      coords, self.pixelDims).compute()
             else:
                 #volume = ms.getVolume(self.skelRadii, coords, self.pixelDims)
                 volume = ms.getVolumeCylinder(radius, segLength)
```

**Comment by jxchen01** [comment]
thanks @mareikethies! We really appreciate your feedback. Would you be interested in making a pull request to the repo?

**Comment by philippa1812** [comment]
thanks for your pull request @mareikethies! I've merged your changes in https://github.com/RUB-Bioinf/VesselExpress/commit/3f828479975534f12a5d173206179cb6b018d60b, so I will close this issue.
